name: Execute Linter

on: [ push ]

jobs:
  static-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: php-actions/composer@v6

      - name: PHP-CS-Fixer
        uses: docker://oskarstark/php-cs-fixer-ga
